name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=react-tourism-${{ github.run_number }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-tourism:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-tourism:${{ env.IMAGE_TAG }}

      - name: Trigger Infra Repo Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: OletiSatishKumar/Tourism_website_Infra
          event-type: update-infra
          client-payload: |
            {
              "image_tag": "${{ env.IMAGE_TAG }}"
            }
