name: Build and Deploy

on:
  push:
    branches:
      - master
      - dev

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  GH_INFRA_REPO: OletiSatishKumar/Tourism_website_Infra_2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag and repo name
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=prod-latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev-latest" >> $GITHUB_OUTPUT
          fi

          repo_name="${DOCKER_USER}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')"
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.tag }} .
          docker push ${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.tag }}

      - name: Clone Infra repo and update image tag
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "github-actions"

          git clone https://x-access-token:${{ secrets.GIT_TKN }}@github.com/${{ env.GH_INFRA_REPO }}.git infra-repo
          cd infra-repo/charts/react

          if [[ "${{ steps.vars.outputs.tag }}" == "prod-latest" ]]; then
            sed -i 's|tag: .*|tag: prod-latest|' values-prod.yaml
          else
            sed -i 's|tag: .*|tag: dev-latest|' values-dev.yaml
          fi

          if ! git diff --quiet; then
            git add .
            git commit -m "Update image tag to ${{ steps.vars.outputs.tag }} [CI]"
            git push
          else
            echo "No changes to commit."
          fi
