name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/tourism-react

    steps:
    - name: Checkout App Code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Vite App
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Image Tag
      id: vars
      run: echo "tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ steps.vars.outputs.tag }}

    - name: Clone Infra Repository
      uses: actions/checkout@v3
      with:
        repository: OletiSatishKumar/Tourism_website_Infra
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: infra

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image:.*|image: ${DOCKER_IMAGE}:${{ steps.vars.outputs.tag }}|" infra/k8s/deployment.yaml

    - name: Commit and Push Updated Manifest
      run: |
        cd infra
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ steps.vars.outputs.tag }}"
        git push
